name: Trigger auto deployment for recipiesnstuff-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/recipiesnstuff-container-app-AutoDeployTrigger-c2ca70fc-e7a6-4ce7-ad0d-1d7e39516c18.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cbdevcontainerreg.azurecr.io
          username: ${{ secrets.RECIPIESNSTUFFCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.RECIPIESNSTUFFCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cbdevcontainerreg.azurecr.io/recipiesnstuff-container-app:${{ github.sha }}
          file: ./dockerfile/Dockerfile
          context: ./dockerfile/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RECIPIESNSTUFFCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n recipiesnstuff-container-app -g Nias-container-app --server cbdevcontainerreg.azurecr.io --username  ${{ secrets.RECIPIESNSTUFFCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.RECIPIESNSTUFFCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n recipiesnstuff-container-app -g Nias-container-app --image cbdevcontainerreg.azurecr.io/recipiesnstuff-container-app:${{ github.sha }}
