name: Trigger auto deployment for wtf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wtf-AutoDeployTrigger-81c102d4-daaf-4402-b625-79425d6ced38.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cbdevcontainerreg.azurecr.io
          username: ${{ secrets.WTF_REGISTRY_USERNAME }}
          password: ${{ secrets.WTF_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cbdevcontainerreg.azurecr.io/recipiesNStuffContainer:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WTF_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n wtf -g Nias-container-app --server cbdevcontainerreg.azurecr.io --username  ${{ secrets.WTF_REGISTRY_USERNAME }} --password ${{ secrets.WTF_REGISTRY_PASSWORD }}
            az containerapp update -n wtf -g Nias-container-app --image cbdevcontainerreg.azurecr.io/recipiesNStuffContainer:${{ github.sha }}
